repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: Rust formatting
        entry: bash -c 'cd capture-engine && cargo fmt --all -- --check'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: Rust linting
        entry: bash -c 'cd capture-engine && cargo clippy -- -D warnings'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-audit
        name: Rust security audit
        entry: bash -c 'cd capture-engine && cargo audit'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: Rust tests
        entry: bash -c 'cd capture-engine && cargo test'
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-deny
        name: Rust dependency check
        entry: bash -c 'cd capture-engine && cargo deny check --config cargo-deny.toml'
        language: system
        types: [rust]
        pass_filenames: false
