[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "Unicode-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
skip = [
    { name = "windows-sys" }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
