# pyproject.toml
[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gotstate"
license = "MIT"
authors = [
    {name = "Brad Edwards", email = "brad@keplerops.com"}
]

[tool.black]
line-length = 120
target-version = ["py310"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v --cov=hsm --cov-report=term-missing"
testpaths = ["hsm/tests"]  # Update this to point to the correct test directory
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]

[tool.coverage.report]
show_missing = true
fail_under = 80

[tool.coverage.run]
source = ["hsm"]
branch = true
