name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install --with dev
      - name: Check code format with black
        run: |
          poetry run black --check gotstate tests
      - name: Verify import order with isort
        run: |
          poetry run isort --check-only --profile black gotstate tests
      - name: Lint with flake8
        run: |
          poetry run flake8 gotstate tests
      - name: Type check with mypy
        run: |
          poetry run mypy gotstate
